ARG IMAGE
ARG WORKSPACE

FROM 684288478426.dkr.ecr.us-east-1.amazonaws.com/verl:ngc-cu124-vllm0.8.5-sglang0.4.6-mcore0.12.0-te2.3-install-aws-20250531

# Install awscli and dependencies (if not already)
RUN pip install boto3
RUN pip install awscli ujson trafilatura 
RUN pip install pathvalidate smolagents mammoth markdownify python-pptx pdfminer.six
RUN pip install puremagic pydub requests SpeechRecognition beautifulsoup4 youtube-transcript-api
RUN pip install html2text jieba
RUN pip install -U crawl4ai
RUN crawl4ai-setup || true  # avoid breaking build if setup needs interactive env
RUN crawl4ai-doctor || true
RUN apt update && apt install -y tmux screen

RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader punkt_tab

WORKDIR /ebs-basemodeling/siyuanxu/tool_synthetic/RL_training/verl_toolmock

#python examples/data_preprocess/multiturn_tool.py

# python -m tests.workers.rollout.my_test_tool_completion_callback > out.txt 2>&1
# bash my_examples/training_rl_tool_mock_8b.sh > out.txt 2>&1
# PYTHONPATH=$(pwd) python scripts/legacy_model_merger.py merge \
#   --backend fsdp \
#    --local_dir '/ebs-basemodeling/siyuanxu/tool_synthetic/RL_training/verl_output/checkpoints/toolmock_async_rl/qwen3-8b-toolmock-turns_20_20250803_170209/global_step_50/actor' \
#    --target_dir '/ebs-basemodeling/siyuanxu/tool_synthetic/RL_training/verl_output/checkpoints/toolmock_async_rl/qwen3-8b-toolmock-turns_20_20250803_170209/global_step_50/model/' \
#    --hf_model_path 'Qwen/Qwen3-8B' 

# PYTHONPATH=$(pwd) python scripts/legacy_model_merger.py merge \
#   --backend fsdp \
#    --local_dir '/fsx-pretraining/home/siyuanxu/tool_synthetic/RL_training/verl_output/checkpoints/toolmock_async_rl/qwen2_5-7b-toolmock-grpo_rollout8_20250819_053934/global_step_90/actor' \
#    --target_dir '/fsx-pretraining/home/siyuanxu/tool_synthetic/RL_training/verl_output/checkpoints/toolmock_async_rl/qwen2_5-7b-toolmock-grpo_rollout8_20250819_053934/global_step_90/model/' \
#    --hf_model_path 'Qwen/Qwen2.5-7B-Instruct' 