hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 18432
  max_response_length: 2048
  train_batch_size: 512
  val_batch_size: 256
  truncation: error
  return_raw_chat: true
  filter_overlong_prompts: false
  custom_cls:
    path: pkg://recipe/bfcl_meta/meta_dataset
    name: BFCLMetaPairDataset

actor_rollout_ref:
  rollout:
    mode: async
    temperature: 1.0
    prompt_length: 18432
    response_length: 2048
    max_model_len: 22528
    n: 8
    gpu_memory_utilization: 0.7
    multi_turn:
      enable: true
      max_assistant_turns: 50
      support_max_model_len: 16384
      summary_safety_margin: 1024
      disable_query_memo: false
      support_temperature: 1.0
      query_temperature: 1.0
      val_support_temperature: 0.0
      val_query_temperature: 0.0
      pipeline_mode: phased
      val_pipeline_mode: summary_only
      summary_phase_epochs: 3
      support_phase_epochs: 0
      tool_config_path: null
      completion_callback: recipe.bfcl_meta.meta_callback.BFCLMetaCompletionCallback
      format: hermes
    val_kwargs:
      temperature: 0.0

reward_model:
  reward_manager: naive

custom_reward_function:
  path: pkg://recipe/bfcl_meta/meta_reward
  name: compute_score

trainer:
  save_best_val_checkpoint_only: false
  best_checkpoint_metric: null
